modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/${mod_repository}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL = "https://hi.auioc.org/arnicalib-mcmod/update/1.20.4.json"
displayURL = "http://hi.auioc.org/arnicalib-mcmod/"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="arnicalib.mixin.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
